name: Generar IPA sin firmar

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  build:
    name: Compilar iOS
    # CAMBIO 1: Fijamos macos-14 para usar una versión estable de Xcode que no rompa Expo
    runs-on: macos-14 

    steps:
      - name: Descargar el código fuente
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          # CAMBIO 2: Actualizamos a Node 24 para cumplir con las nuevas reglas de GitHub
          node-version: 24 

      - name: Instalar dependencias del proyecto
        run: npm install

      - name: Generar carpetas nativas de Expo (Prebuild)
        run: npx expo prebuild --platform ios --clean

      - name: Compilar aplicación sin firmas digitales
        run: |
          cd ios
          
          export NODE_BINARY=$(which node)
          sudo ln -sf $(which node) /usr/local/bin/node
          
          WORKSPACE=$(ls -d *.xcworkspace | head -n 1)
          SCHEME=$(basename "$WORKSPACE" .xcworkspace)
          echo "Construyendo Workspace: $WORKSPACE con Scheme: $SCHEME"
          
          xcodebuild build \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath derivedData \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            GCC_TREAT_WARNINGS_AS_ERRORS=NO

      - name: Empaquetar en formato .ipa
        run: |
          cd ios
          mkdir -p Payload
          mv derivedData/Build/Products/Release-iphoneos/*.app Payload/
          zip -r GymTracker.ipa Payload

      - name: Subir el archivo IPA para descargar
        uses: actions/upload-artifact@v4
        with:
          name: GymTracker-App
          path: ios/GymTracker.ipa